# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Procesamiento de Lenguaje Natural
site_url: https://fdiaz1968.github.io/NLP/
site_author: Fernando Díaz H., PhD.
site_description: Análisis Textual con R y Python — UTFSM / Universidad del Pacífico

# Repository
repo_name: fdiaz1968/NLP
repo_url: https://github.com/fdiaz1968/NLP
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo_utfsm.png
  favicon: images/logo_utfsm.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fdiaz1968
    - icon: fontawesome/solid/envelope
      link: mailto:fernando.diaz@usm.cl

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - Program:
        - programa.md
    - Classes:
        - clases/clases.md
    - Exercises:
        - exercises/exercises.md
    - Datasets:
        - datasets/datasets.md
    - Assessments:
        - "📊 Proyecto Integrador": assessments/proyecto_integrador.md
    - Notas:
        - notas/notas.md
